global_costmap:
  # Costmap_2d parameters
  global_frame: /map
  robot_base_frame: /base_footprint
  update_frequency: 1.0
  publish_frequency: 0.5
  static_map: true
  transform_tolerance: 0.5
  width: 100
  height: 100
  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
   
   
  static_layer:
    enabled: true
    unknown_cost_value: -1
    lethal_cost_value: 100
    map_topic: "map"
    first_map_only: false
    subcribe_to_updates: false
    track_unknown_space: true
    use_maximum: false
    trinary_costmap: true

  obstacle_layer:
    enabled: true
    # combination_method:   1       Used for ObstacleCostmapPlugin
    # track_unknown_space:  true
    # Global Parameters applied to all sensors
    max_obstacle_height: 1.8
    obstacle_range: 2.5
    raytrace_range: 3.0
    # VoxelCostmapPlugin Parameters
    origin _z: 0.0
    z_resolution: 0.2
    z_voxels: 2
    unknown_threshold: 2
    mark_threshold: 0   
    footprint_clearing_enabled: true
    observation_sources: zed_cam  # scan
      #  scan:
      #     data_type: LaserScan
      #     topic: /scan_filtered
      #     marking: true              # Only used by local costmap
      #     clearing: true             # Has to free up space for local planner is path is avalible
      #     min_obstacle_height: 0.0
      #     max_obstacle_height: 2.0
    zed_cam:
      data_type: PointCloud2
      topic: /rtabmap/cloud_map
      marking: true
      clearing: false
      min_obstacle_height: 0.0
      max_obstacle_height: 2.0
    
    inflation_layer:
      enabled: true
      inflation_radius: 0.55
      cost_scaling_factor: 3.0