---
# Visit http://wiki.ros.org/teb_local_planner for information regarding values
TebLocalPlannerROS:

  odom_topic: odom
  map_frame: /map

  # Trajectory

  teb_autosize: true
  dt_ref: 0.3
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: true
  max_global_plan_lookahead_dist: 3.0
  feasibility_check_no_poses: 5

  # Robot

  cmd_angle_instead_rotvel: true
  max_vel_x: 1.0
  max_vel_x_backwards: 0.01
  max_vel_theta: 0.3
  acc_lim_x: 1.5
  acc_lim_theta: 1.1
  min_turning_radius: 4.0
  wheelbase: 1.8
  footprint_model:
    # types: "point", "circular", "two_circles", "line", "polygon"
    type: circular
    radius: 0.2

  # GoalTolerance

  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.1
  free_goal_vel: false

  # Obstacles

  min_obstacle_dist: 0.16
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 0.35
  obstacle_poses_affected: 30
  costmap_converter_plugin: ''
  costmap_converter_spin_thread: true
  costmap_converter_rate: 5

  # Optimization

  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: true
  optimization_verbose: false
  penalty_epsilon: 0.1
  weight_max_vel_x: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 1000
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 1
  weight_obstacle: 50
  weight_dynamic_obstacle: 10  # not in use yet
  alternative_time_cost: false  # not in use yet

  # Homotopy Class Planner

  enable_homotopy_class_planning: true
  enable_multithreading: false
  simple_exploration: false
  max_number_classes: 4
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: false
