include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

stages:
  - build

build-dbw-node-firmware:
  image: git-registry.cooperigvc.org/igvc/selfdrive/dbw/node_fw:latest
  stage: build
  script:
    - ./setup.sh
    - source .venv/bin/activate && make can
    - source .venv/bin/activate && make dbw/node_fw
  artifacts:
    paths:
      - can/{igvc_can.dbc,can_gen.c,can_gen.h}
      - dbw/node_fw/.pio/build/*/firmware.{bin,elf}
