# Constants for the individual follower module

[Individual_Follower]
NWINDOWS = 9
SEARCH_WIDTH = 100
MINPIXELS = 40
LANE_POLY_SIZE = 2
BOX_COLOR = [0, 255, 0]
LANE_COLOR = [255, 0, 0]
DRAW_THICKNESS = 2
