name: C/C++ CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: install libsocketcan
      run: sudo ./tools/install-libsocketcan.sh
    - name: make
      run: make
