Import('env')

# Make DBC ------------------------------------------------
GENERATED_DBC   = env.File('igvc_can.dbc')
CAN_YML         = env.File('can.yml')
DBC_EMITTER     = env.File('create-dbc.py')

# Make emitter script
env.Command(
    DBC_EMITTER,
    [env['OPENCAN_CLI'], CAN_YML],
    f'$OPENCAN_CLI compose {CAN_YML} --dump-python > $TARGET'
)

# Make DBC by running emitter script
[dbc_builder] = env.Command(
    GENERATED_DBC,
    DBC_EMITTER,
    [f'python3 {DBC_EMITTER.path}',
     Move("$TARGET", "opencan.dbc")]
)
env.Depends(dbc_builder, env['PIP_PACKAGES'])

env.Alias('dbc', dbc_builder)
env['AddHelp']('dbc', 'Build igvc_can.dbc')
# ---------------------------------------------------------
