Import('env')

OPENCAN_BIN     = env.File('$REPO_ROOT/build/cargo/bin/opencan-cli')
GENERATED_DBC   = env.File('igvc_can.dbc')
CAN_YML         = env.File('can.yml')

DBC_EMITTER     = env.File('create-dbc.py')

# Make emitter script
[dbc_emitter] = env.Command(
    DBC_EMITTER,
    CAN_YML,
    f'{OPENCAN_BIN} compose $SOURCE --dump-python > $TARGET'
)

# Make DBC by running emitter script
[dbc] = env.Command(
    GENERATED_DBC,
    DBC_EMITTER,
    [f'python3 {DBC_EMITTER.path}',
     Move("$TARGET", "opencan.dbc")]
)

env.Alias('dbc', dbc)
