# https://docs.docker.com/compose/gpu-support/
version: '3'

services:
    master:
        build: docker-master/.
        container_name: master
        tty: true
        environment:
            - 'ROS_HOSTNAME=master'
            - 'ROS_MASTER_URI=http://master:11311'
            - 'DISPLAY=$DISPLAY'
            - 'QT_X11_NO_MITSHM=1'
        volumes:
            - '/tmp/.X11-unix:/tmp/.X11-unix'
        restart: unless-stopped
        command: stdbuf -o L roscore

    rplidar:
        build: docker-rplidar/.
        container_name: rplidar
        tty: true
        environment:
            - 'ROS_HOSTNAME=rplidar'
            - 'ROS_MASTER_URI=http://master:11311'
            - 'DISPLAY=$DISPLAY'
            - 'QT_X11_NO_MITSHM=1'
        volumes:
            - '/tmp/.X11-unix:/tmp/.X11-unix'
        devices:
            - '/dev/ttyUSB0:/dev/ttyUSB0'
        command: roslaunch rplidar_ros view_rplidar.launch
        depends_on:
            - master
    
    gazebo:
        build: docker-gazebo/.
        container_name: gazebo
        tty: true
        environment:
            - 'ROS_HOSTNAME=gazebo'
            - 'ROS_MASTER_URI=http://master:11311'
            - 'DISPLAY=$DISPLAY'
            - 'QT_X11_NO_MITSHM=1'
        volumes:
            - '/tmp/.X11-unix:/tmp/.X11-unix'
        command: roslaunch turtlebot3_gazebo turtlebot3_house.launch
        restart: unless-stopped
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]

    zed:
        build: docker-zed/.
        container_name: zed
        tty: true
        privileged: true
        environment:
            - 'ROS_HOSTNAME=zed'
            - 'ROS_MASTER_URI=http://master:11311'
            - 'DISPLAY=$DISPLAY'
            - 'QT_X11_NO_MITSHM=1'
        volumes:
            - '/tmp/.X11-unix:/tmp/.X11-unix'
#        devices:
#            - '/dev/ttyUSB0:/dev/ttyUSB0'
        # command: roslaunch zed_wrapper zed.launch
        # command: roslaunch zed_display_rviz display_zed.launch
        command: roslaunch zed_rtabmap_example zed_rtabmap.launch
        depends_on:
            - master
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
        restart: unless-stopped

    teleop:
        build: docker-teleop/.
        container_name: teleop
        tty: true
        environment:
            - 'ROS_HOSTNAME=teleop'
            - 'ROS_MASTER_URI=http://master:11311'
        #     - 'DISPLAY=$DISPLAY'
        #     - 'QT_X11_NO_MITSHM=1'
        # volumes:
        #     - '/tmp/.X11-unix:/tmp/.X11-unix'
        # command: roslaunch rplidar_ros view_rplidar.launch
        depends_on:
            - master