# https://docs.docker.com/compose/gpu-support/
version: '3'

services:
    master:
        build: docker/master/.
        container_name: master
        tty: true
        environment:
            - 'ROS_HOSTNAME=master'
            - 'ROS_MASTER_URI=http://master:11311'
            - 'DISPLAY=$DISPLAY'
            - 'QT_X11_NO_MITSHM=1'
        ports:
            - '11311:11311'
        volumes:
            - '/tmp/.X11-unix:/tmp/.X11-unix'
        restart: unless-stopped
        command: stdbuf -o L roscore

    redis:
        image: redis:7.0-alpine
        container_name: redis
        restart: unless-stopped
        ports:
            - '6379:6379'

    twist:
        build: docker/cmd_to_ctrl/.
        container_name: twist
        tty: true
        environment:
            - 'ROS_HOSTNAME=navigation'
            - 'ROS_MASTER_URI=http://master:11311'
        volumes:
            - './docker/cmd_to_ctrl/send_launch:/app/ros_ws/src/send_launch'
            - '../common/cand:/app/cand'
        depends_on:
            - master

    navigation:
        build: docker/navigation/.
        container_name: navigation
        tty: true
        environment:
            - 'ROS_HOSTNAME=navigation'
            - 'ROS_MASTER_URI=http://master:11311'
        volumes:
            - './docker/navigation/scooter_launch:/app/ros_ws/src/scooter_launch'

    py-steering:
        build: docker/py-steering/.
        container_name: py-steering
        tty: true
        privileged: true
        volumes:
            - '../dbw/py-steering:/app/py-steering'
        depends_on:
            - redis

    velodyne:
        build: docker/3dlidar/.
        container_name: velodyne
        tty: true
        environment:
            - 'ROS_HOSTNAME=velodyne'
            - 'ROS_MASTER_URI=http://master:11311'
            - 'DISPLAY=$DISPLAY'
            - 'QT_X11_NO_MITSHM=1'
        volumes:
            - '/tmp/.X11-unix:/tmp/.X11-unix'
        depends_on:
            - master
        volumes:
            - './docker/3dlidar/3dlidar_launch:/app/ros_ws/src/3dlidar_launch'
        ports:
            - 2368:2368/udp
            - 8308:8308/udp

    rplidar:
        build: docker/rplidar/.
        container_name: rplidar
        tty: true
        environment:
            - 'ROS_HOSTNAME=rplidar'
            - 'ROS_MASTER_URI=http://master:11311'
            - 'DISPLAY=$DISPLAY'
            - 'QT_X11_NO_MITSHM=1'
        volumes:
            - '/tmp/.X11-unix:/tmp/.X11-unix'
        devices:
            - '/dev/ttyUSB0:/dev/ttyUSB0'
        command: roslaunch rplidar_ros view_rplidar.launch
        depends_on:
            - master

    zed:
        build: docker/zed/.
        #image: git-registry.cooperigvc.org/igvc/selfdrive/ros/zed:0.1
        container_name: zed
        tty: true
        privileged: true
        environment:
            - 'ROS_HOSTNAME=zed'
            - 'ROS_MASTER_URI=http://master:11311'
            - 'DISPLAY=$DISPLAY'
            - 'QT_X11_NO_MITSHM=1'
        volumes:
            - '/tmp/.X11-unix:/tmp/.X11-unix'
            - './docker/zed/zed_launch:/app/ros_ws/src/zed_launch'
        # depends_on:
        #     - master
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
        restart: unless-stopped

    rviz:
        build: docker/rviz/.
        container_name: rviz
        tty: true
        environment:
            - 'ROS_HOSTNAME=rviz'
            - 'ROS_MASTER_URI=http://master:11311'
            - 'DISPLAY=$DISPLAY'
            - 'QT_X11_NO_MITSHM=1'
        volumes:
            - '/tmp/.X11-unix:/tmp/.X11-unix'
        #command: rviz
        depends_on:
            - master

    rtabmap:
        build: docker/rtabmap/.
        container_name: rtabmap
        tty: true
        privileged: true
        environment:
            - 'ROS_HOSTNAME=rtabmap'
            - 'ROS_MASTER_URI=http://master:11311'
            - 'DISPLAY=$DISPLAY'
            - 'QT_X11_NO_MITSHM=1'
        volumes:
            - '/tmp/.X11-unix:/tmp/.X11-unix'
            #- ~/.ros:/root
            - './docker/rtabmap/rtabmap_launch:/app/ros_ws/src/rtabmap_launch'
        depends_on:
            - master
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]

    gps:
        build: docker/gps/.
        container_name: gps
        tty: true
        privileged: true
        environment:
            - 'ROS_HOSTNAME=gps'
            - 'ROS_MASTER_URI=http://master:11311'
            - 'DISPLAY=$DISPLAY'
            - 'QT_X11_NO_MITSHM=1'
        volumes:
            - '/tmp/.X11-unix:/tmp/.X11-unix'
        depends_on:
            - master

    imu:
        build: docker/imu/.
        container_name: imu
        tty: true
        environment:
            - 'ROS_HOSTNAME=imu'
            - 'ROS_MASTER_URI=http://master:11311'
        volumes:
            - './docker/imu:/app/ros_ws/src/imu'
        depends_on:
            - master
