version: '3'

services:
    master:
        image: ros:noetic-ros-core-focal
        container_name: master
        tty: true
        environment:
            - 'ROS_HOSTNAME=master'
            - 'ROS_MASTER_URI=http://master:11311'
        restart: unless-stopped
        command: stdbuf -o L roscore

    rplidar:
        build: docker-rplidar/.
        container_name: rplidar
        tty: true
        environment:
            - 'ROS_HOSTNAME=rplidar'
            - 'ROS_MASTER_URI=http://master:11311'
        devices:
            - '/dev/ttyUSB0:/dev/ttyUSB0'
        command: roslaunch rplidar_ros rplidar.launch
        depends_on:
            - master
    
    gzserver:
        build: docker-gzserver/.
        container_name: gzserver
        tty: true
        environment:
            - 'ROS_HOSTNAME=gzserver'
            - 'ROS_MASTER_URI=http://master:11311'
            - 'DISPLAY=$DISPLAY'
            - 'QT_X11_NO_MITSHM=1'
        volumes:
            - '/tmp/.X11-unix:/tmp/.X11-unix'
        command: roslaunch turtlebot3_gazebo turtlebot3_house.launch
        restart: unless-stopped
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]

        depends_on:
            - master