local_costmap:
   # Costmap_2d parameters
   global_frame: /zed/zed_node/odom
   robot_base_frame: /base_footprint
   update_frequency: 5.0
   publish_frequency: 2.0
   static_map: false
   rolling_window: true
   width: 6.0
   height: 6.0
   resolution: 0.06
   transform_tolerance: 0.5
   plugins:
    - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
   #  - {name: person_layer,        type: "social_navigation_layers::ProxemicLayer"}
    

   obstacle_layer:
      enabled: true
      # combination_method:   1       Used for ObstacleCostmapPlugin
      # track_unknown_space:  true
      # Global Parameters applied to all sensors
      max_obstacle_height: 1.8
      obstacle_range: 2.5
      raytrace_range: 3.0
      # VoxelCostmapPlugin Parameters
      origin _z: 0.0
      z_resolution: 0.2
      z_voxels: 2
      unknown_threshold: 2
      mark_threshold: 0   
      footprint_clearing_enabled: true
      observation_sources: scan #zed_cam
      scan:
         data_type: LaserScan
         topic: /scan_filtered
         marking: true              # Only used by local costmap
         clearing: true             # Has to free up space for local planner is path is avalible
         min_obstacle_height: 0.0
         max_obstacle_height: 2.0
      # zed_cam:
      #    data_type: PointCloud2
      #    topic: /rtabmap/cloud_map
      #    marking: true
      #    clearing: false
      #    min_obstacle_height: 0.0
      #    max_obstacle_height: 2.0
   
   inflation_layer:
      enabled: true
      inflation_radius: 0.6
      cost_scaling_factor: 2.0
   
   # person_layer:
   #    enabled: true
   #    cuttoff: 10.0
   #    amplitude: 77.0
   #    covariance: 0.25
   #    factor: 5.0
   #    keep_time: 0.75