---

name: mdbook

# yamllint disable-line rule:truthy
on:
  pull_request: ~

jobs:
  checkout:
    uses: ./.github/workflows/checkout.yml

  build:
    needs: checkout
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/checkout

      - name: Build docs
        run: mdbook build

      - name: Deploy docs
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build/docs
          FOLDER: build/docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_EMPTY_COMMITS: true
          MESSAGE: '{long-sha}'
