---

name: mdbook

# yamllint disable-line rule:truthy
on:
  pull_request: ~

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install latest version of `mdbook`
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: latest

      - name: Build docs
        run: mdbook build
