name: Build node_bl

# node_bl job triggers disabled for now while bootloader is under rework
# on: [pull_request, push, workflow_dispatch]
on: workflow_dispatch

jobs:
  pre_job:
    runs-on: ubuntu-latest

    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}

    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v4

  build:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}

    runs-on: ubuntu-22.04
    container:
      image: dmezh/igvc-nodefw-builder

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cache .pio
        id: cache-pio-build-dir
        uses: actions/cache@v3
        with:
          path: dbw/node_bl/.pio
          key: pio_cache

      - name: Run setup
        run: ./setup.sh

      - name: Build firmware
        run: . .venv/bin/activate && make dbw/node_bl

      - name: 'Upload CAN network'
        uses: actions/upload-artifact@v3
        with:
          name: can-dbc
          path: build/can/igvc_can.dbc

      - name: 'Upload firmware binaries'
        uses: actions/upload-artifact@v3
        with:
          name: node_bl-bin
          path: dbw/node_bl/.pio/build/*/firmware.bin
