---

name: pre-commit

# yamllint disable-line rule:truthy
on:
  - pull_request
  - push

jobs:
  checkout:
    uses: ./.github/workflows/checkout.yml

  pre-commit:
    needs: checkout
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/checkout

      - run: pre-commit run --show-diff-on-failure --color=always
